In [1]:
import cv2 as cv
import numpy as np


In [18]:

gray_img = np.array(cv.imread('OpencvGrauwertKeil.png'))
gray_img = gray_img.astype('float32')

white_contents = gray_img[50:430, 5:25]
gray_contents = gray_img[50:430, 150:170]
gray_contents2 = gray_img[50:430, 300:320]
gray_contents3 = gray_img[50:430, 400:420]
black_contents = gray_img[50:430, 600:620]


sub_image_lst = [white_contents, gray_contents,
                 gray_contents2, gray_contents3, black_contents]


cv.imwrite(".//whitecontents.png", white_contents.astype('uint8'))
cv.imwrite(".//gray_contents.png", gray_contents.astype('uint8'))
cv.imwrite(".//gray_contents2.png", gray_contents2.astype('uint8'))
cv.imwrite(".//gray_contents3.png", gray_contents3.astype('uint8'))
cv.imwrite(".//black_contents.png", black_contents.astype('uint8'))





True

In [19]:
# concat pics horizontally

img_h = cv.hconcat([white_contents, gray_contents,
                   gray_contents2, gray_contents3, black_contents])

cv.imwrite(".//horizontalCat.png", img_h.astype('uint8'))


True

In [23]:
for e in sub_image_lst:
    
    print("STD: %f  |  MEAN: %f" % ( np.std(e), np.mean(e) ) )

STD: 11.796647  |  MEAN: 203.926971
STD: 9.905970  |  MEAN: 160.988647
STD: 5.930073  |  MEAN: 119.647545
STD: 6.935028  |  MEAN: 74.292587
STD: 3.144824  |  MEAN: 32.350174


In [52]:
dunkelbilder = []

counter = 1

param = 'OpencvDunkelBild' + str(counter) + '.png'

for e in range (1,10):

    dunkelbilder.append(np.array(cv.imread(param)))
    counter+1
    pixel_mean = np.mean(dunkelbilder,axis=0)

#print(pixel_mean)
cv.imwrite('.//dunkelbildmean.png' , pixel_mean.astype('uint8'))


True

In [59]:
input_black = np.array(cv.imread('dunkelbildmean.png'))
input_black = input_black.astype('float32')

our_black = np.array(cv.imread('OpencvDunkelBild1.png'))
our_black = our_black.astype('float32')

result = np.subtract(our_black, input_black)
print(result)

cv.imwrite('.//resultBlack.png', result.astype('uint8'))


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 ...

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  ...
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


True

In [60]:
weißbilder = []

counter = 1

param = 'Opencvweisbild' + str(counter) + '.png'

for e in range(1, 10):

    weißbilder.append(np.array(cv.imread(param)))
    counter+1
    weis_pixel_mean = np.mean(weißbilder, axis=0)

#print(weis_pixel_mean)
cv.imwrite('.//weisbildmean.png', weis_pixel_mean.astype('uint8'))


True

In [68]:
input_weis = np.array(cv.imread('weisbildmean.png'))
input_weis = input_weis.astype('float32')

our_weis = np.array(cv.imread('Opencvweisbild1.png'))
our_weis = our_weis.astype('float32')


sub_black_white = np.subtract(input_weis, our_black)
cv.imwrite('.//sub_black_white.png', sub_black_white.astype('uint8'))


meanwhite = np.divide(our_weis, np.mean(our_weis)) # normiert Mittelwert zu 1

#print(meanwhite)
cv.imwrite('.//meanwhite.png', meanwhite.astype('uint8'))

result_black_white = sub_black_white/meanwhite

#print(result_black_white)

cv.imwrite('.//result_black_white.png', result_black_white.astype('uint8'))


True